import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          style={{
            width: "100%",
            background: "teal",
            justifyContent: "center",
            alignItems: "center",
            fontSize: "50px",
            margin: "0",
            padding: "0",
            listStyle: "none",
            textDecoration: "none",
            display: "flex",
          }}
        >
          <Link
            style={{
              margin: "10px",
              padding: "0",
              textDecoration: "none",
              listStyle: "none",
              color: "white",
            }}
            href={"/Posts"}
          >
            <p
              style={{
                margin: "10px",
                padding: "0",
                textDecoration: "none",
                listStyle: "none",
              }}
            >
              Posts
            </p>
          </Link>
          <Link
            style={{
              margin: "10px",
              padding: "0",
              textDecoration: "none",
              listStyle: "none",
              color: "white",
            }}
            href={"/Posts"}
          >
            <p
              style={{
                margin: "10px",
                padding: "0",
                textDecoration: "none",
                listStyle: "none",
              }}
            >
              Articles
            </p>
          </Link>
          <Link
            style={{
              margin: "10px",
              padding: "0",
              textDecoration: "none",
              listStyle: "none",
              color: "white",
            }}
            href={"/Posts"}
          >
            <p
              style={{
                margin: "10px",
                padding: "0",
                textDecoration: "none",
                listStyle: "none",
              }}
            >
              Home
            </p>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
